/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.login.dbloan;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomerInfo generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Customer_info`")
public class CustomerInfo implements Serializable {

    private String aadhaarCard;

    @Id
    @Column(name = "`Aadhaar_Card`", nullable = false, length = 255)
    public String getAadhaarCard() {
        return this.aadhaarCard;
    }

    public void setAadhaarCard(String aadhaarCard) {
        this.aadhaarCard = aadhaarCard;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CustomerInfo)) return false;
        final CustomerInfo customerInfo = (CustomerInfo) o;
        return Objects.equals(getAadhaarCard(), customerInfo.getAadhaarCard());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAadhaarCard());
    }
}