/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.login.dbloan;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Customer generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Customer`")
public class Customer implements Serializable {

    private Integer customerid;
    private String firstName;
    private String middleName;
    private String lastName;
    private Date birthDate;
    private String aadhaarCard;
    private String panCard;
    private String occupation;
    private String gender;
    private String currentResidence;
    private String currentCity;
    private int pincode;
    private String loanType;
    private String addInformation;
    private CustomerInfo customerInfo;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`customerid`", nullable = false, scale = 0, precision = 10)
    public Integer getCustomerid() {
        return this.customerid;
    }

    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    @Column(name = "`FirstName`", nullable = false, length = 255)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "`MiddleName`", nullable = true, length = 255)
    public String getMiddleName() {
        return this.middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    @Column(name = "`LastName`", nullable = false, length = 255)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "`Birth_Date`", nullable = false)
    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    @Column(name = "`Aadhaar_Card`", nullable = false, length = 255)
    public String getAadhaarCard() {
        return this.aadhaarCard;
    }

    public void setAadhaarCard(String aadhaarCard) {
        this.aadhaarCard = aadhaarCard;
    }

    @Column(name = "`PAN_Card`", nullable = false, length = 255)
    public String getPanCard() {
        return this.panCard;
    }

    public void setPanCard(String panCard) {
        this.panCard = panCard;
    }

    @Column(name = "`Occupation`", nullable = false, length = 255)
    public String getOccupation() {
        return this.occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    @Column(name = "`Gender`", nullable = false, length = 255)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "`Current_Residence`", nullable = false, length = 255)
    public String getCurrentResidence() {
        return this.currentResidence;
    }

    public void setCurrentResidence(String currentResidence) {
        this.currentResidence = currentResidence;
    }

    @Column(name = "`Current_City`", nullable = false, length = 255)
    public String getCurrentCity() {
        return this.currentCity;
    }

    public void setCurrentCity(String currentCity) {
        this.currentCity = currentCity;
    }

    @Column(name = "`Pincode`", nullable = false, scale = 0, precision = 10)
    public int getPincode() {
        return this.pincode;
    }

    public void setPincode(int pincode) {
        this.pincode = pincode;
    }

    @Column(name = "`Loan_Type`", nullable = false, length = 255)
    public String getLoanType() {
        return this.loanType;
    }

    public void setLoanType(String loanType) {
        this.loanType = loanType;
    }

    @Column(name = "`Add_Information`", nullable = false, length = 255)
    public String getAddInformation() {
        return this.addInformation;
    }

    public void setAddInformation(String addInformation) {
        this.addInformation = addInformation;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`Aadhaar_Card`", referencedColumnName = "`Aadhaar_Card`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`Customer_ibfk_1`"))
    @Fetch(FetchMode.JOIN)
    public CustomerInfo getCustomerInfo() {
        return this.customerInfo;
    }

    public void setCustomerInfo(CustomerInfo customerInfo) {
        if(customerInfo != null) {
            this.aadhaarCard = customerInfo.getAadhaarCard();
        }

        this.customerInfo = customerInfo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Customer)) return false;
        final Customer customer = (Customer) o;
        return Objects.equals(getCustomerid(), customer.getCustomerid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCustomerid());
    }
}